### ISSUE TITLE
crash when starting minecraft

### ISSUE THREAD

**Issue by someonedeepintheinternet** [TonimatasDEV/PotionTimeStacker#4] opened 2023-08-24 16:28 UTC
Basically it crashed with exit code 1, no crash log. just plain exit code 1

**Comment by TonimatasDEV** [comment] 2023-08-24 16:32
What version of Minecraft? What mod loader are you using? What version of Time Stacker are you using? You can send the mod list and the logs? I need this infornation for fix this.

**Comment by TonimatasDEV** [comment] 2023-08-24 16:36
> Basically it crashed with exit code 1, no crash log. just plain exit code 1

Not only exist the crash log, the latest log and the debug log is the most important.

**Comment by someonedeepintheinternet** [comment] 2023-08-24 16:39
where do I find the latest and debug logs? I'm dumb 
 I use fabric-loader-0.14.21-1.20.1

also here is my mod list:
[mods.txt](https://github.com/TonimatasDEV/TimeStacker/files/12431569/mods.txt)

**Comment by TonimatasDEV** [comment] 2023-08-24 16:40
> where do I find the latest and debug logs? I'm dumb 
>  I use fabric-loader-0.14.21-1.20.1
> 
> also here is my mod list:
> [mods.txt](https://github.com/TonimatasDEV/TimeStacker/files/12431569/mods.txt)
> 

In the logs folder.

**Comment by someonedeepintheinternet** [comment] 2023-08-24 16:41
[latest.log](https://github.com/TonimatasDEV/TimeStacker/files/12431585/latest.log)
[debug.log](https://github.com/TonimatasDEV/TimeStacker/files/12431588/debug.log)

**Comment by TonimatasDEV** [comment] 2023-08-24 16:42
> where do I find the latest and debug logs? I'm dumb 
>  I use fabric-loader-0.14.21-1.20.1
> 
> also here is my mod list:
> [mods.txt](https://github.com/TonimatasDEV/TimeStacker/files/12431569/mods.txt)
> 

You have 2 Time Stackers. Delete the Forge TimeStacker

**Comment by someonedeepintheinternet** [comment] 2023-08-24 16:43
wait wha huh

**Comment by someonedeepintheinternet** [comment] 2023-08-24 16:44
well I deleted it but still crashes with exit code 1

**Comment by TonimatasDEV** [comment] 2023-08-24 16:53
> well I deleted it but still crashes with exit code 1

I will try to fix it, the problem is that I am on vacation. I'll leave this open and let you know when it's solved. Thank you very much for telling me the error.

**Comment by someonedeepintheinternet** [comment] 2023-08-24 16:53
sure....take your time

**Comment by TonimatasDEV** [comment] 2023-08-27 18:20
> sure....take your time

Fixed in this version: https://modrinth.com/mod/timestacker/version/JMMJIEjj

**Closed as completed by TonimatasDEV** 2023-08-27 18:20 UTC
